### ISSUE TITLE
"classnames" dependency

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#481]
Some competitors use `classnames` package. I am not sure, what exactly is it it doing (looks like helper for dynamic calculations of style names); but it looks like the same can be done without it, thus we can get rid of this dependency (and, should mention in docs that it should not be used).

**Comment by sushilshinde** [comment]
Looks like a syntactic sugar for conditional statements, the code looks clean with its use.

**Comment by birdofpreyru** [comment]
Yes, it is syntax sugar, and I want to get rid of it, cause it does not look clean for my eye, and with our setup, I believe, we never should use multiple style names in markup. E.g.:
```jsx
styleName={cn('winner', {
                'place-1': w.placement === 1,
                'place-2': w.placement === 2,
                'place-3': w.placement === 3 })}
```
I believe, it is a way better to do instead:
```jsx
styleName={`place-${w.placement}`}
```
and have the rest done in the right way in scss:
```scss
@mixin place {
  // The common place style, which is inside "winner" class now, I guess.
}

.place-1 {
  @include place;

  color: $tc-gold;
}

.place-2 {
  @include place;

  color: $tc-grey;
}

// etc.
```
